name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build and Analyze with SonarCloud
      run: msbuild /t:Rebuild /p:Configuration=Release /p:Platform="Any CPU" /p:AnalysisMode=SonarQube /p:SonarQubeConfigPath=SonarQube.Analysis.xml /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        Solution: 'new-world/OSIsoftPI2AzureEventHub.sln'
